### ISSUE TITLE
Issue - ERROR: script returned exit code 6; when used this script in my Quality Gate Status check

### ISSUE THREAD

**Issue by ak185482** [rickyshelton/sonarqube-quality-gate#1]
I have used the below pipeline script within my multi-branch pipeline, but getting the "ERROR: script returned exit code 6".

stage("Quality Gate Status Check") {
            echo "*** Checking Quality Gate, break the build if failure ***"
            sh """
                dos2unix ./breakbuild.sh
                chmod +x  ./breakbuild.sh
                ./breakbuild.sh https:/sonar.abc.com <token>
            """
        }

**Comment by rickyshelton** [comment]
Hi there,

I'm sorry I won't be able to help with your specific setup, the script was shared as an example to work from.

Just a quick observation though, it's intended that you call the script with 2 arguments - the sonar instance url, and the access token:

`
./breakbuild.sh https:/sonar.ncr.com <your access token>
`

**Comment by ak185482** [comment]
> Hi there,
> 
> I'm sorry I won't be able to help with your specific setup, the script was shared as an example to work from.
> 
> Just a quick observation though, it's intended that you call the script with 2 arguments - the sonar instance url, and the access token:
> 
> `./breakbuild.sh https:/sonar.abc.com <your access token>`

I believe the issue I am facing is due to curl command. can you check it once.

**Comment by rickyshelton** [comment]
Hi @ak185482 - again sorry but no, I cannot provide any specific support for your setup. The script however does rely on curl, jq, and cut being available on the target.
